[project]
name = "deeplearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "d2l>=0.17.0",
    "ipython==8.37.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.1",
]
